/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as openzeppelinSolidity from "./openzeppelin-solidity";
export type { openzeppelinSolidity };
export * as factories from "./factories";
export type { Floppy } from "./contracts/Floppy";
export { Floppy__factory } from "./factories/contracts/Floppy__factory";
export type { Vault } from "./contracts/Vault";
export { Vault__factory } from "./factories/contracts/Vault__factory";
export type { AccessControl } from "./openzeppelin-solidity/contracts/access/AccessControl";
export { AccessControl__factory } from "./factories/openzeppelin-solidity/contracts/access/AccessControl__factory";
export type { Ownable } from "./openzeppelin-solidity/contracts/access/Ownable";
export { Ownable__factory } from "./factories/openzeppelin-solidity/contracts/access/Ownable__factory";
export type { ERC20 } from "./openzeppelin-solidity/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/openzeppelin-solidity/contracts/token/ERC20/ERC20__factory";
export type { ERC20Burnable } from "./openzeppelin-solidity/contracts/token/ERC20/ERC20Burnable";
export { ERC20Burnable__factory } from "./factories/openzeppelin-solidity/contracts/token/ERC20/ERC20Burnable__factory";
export type { IERC20 } from "./openzeppelin-solidity/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/openzeppelin-solidity/contracts/token/ERC20/IERC20__factory";
